version: "3.7"

services:
  fastapi:
    build: .
    container_name: tailor_python
    restart: always
    ports:
      - 3031:3031
    volumes:
      - ./:/server/
    working_dir: /server
    # entrypoint: ["/bin/bash", "-c"]
    command: /bin/bash -c "echo ./requirements.txt"
    command: /bin/bash -c "apt-get update && apt-get upgrade -y && apt-get install neovim tmux -y"
    command: python3 -m pip install --no-cache-dir --upgrade -r ./requirements.txt
    command: python3 -m uvicorn app.main:app --host 0.0.0.0 --port 3031 --reload --reload-dir .
